### ISSUE TITLE
Look at sites where there is no data due to non-detect.  

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/LIQWIDS#106]
Check email with details

**Comment by marsmith** [comment]
There is no email

**Comment by marsmith** [comment]
Hi all,

 

On yesterday’s call I mentioned sometimes only units are listed in the table that’s generated.  Here is an example https://test.wim.usgs.gov/liqwids/?characteristic=Nitrate&site=11NPSWRD_WQX-FIIS_CCES_FP .

 

If you download the CSV results it shows in this case they are all “Not Detected” which is provided in the “ResultDetectionConditionText” field.  I’m wondering if this field + the “ResultMeasureValue” + the “ResultMeasure/MeasureUnitCode” field will always give us what we want in the “Value” column of the portal.

 

Are you also aware that if more than one depth value is included in the results a separate graph is developed providing results by depth?  Here is an example https://test.wim.usgs.gov/liqwids/?characteristic=Nitrate&site=USGS-403535073352801 .  This may be an odd case since the depths are ‘0’ and ‘N/A’, this is probably OK but is this what you expected?

 

Another thought I had, is there a way to include exporting of the graphs?  I can’t remember if this was planned or not.

 

Looking forward to the next test site release.

 

Thanks,

Dan

**Comment by kjacobsen16** [comment]
When ResultDetectionConditionText = "Not Detected", say "Not Detected" instead of having the empty value and measure code.

**Comment by kjacobsen16** [comment]
done
