### ISSUE TITLE
Implement a lookup for HUC 8 names

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/LIQWIDS#113]
User feedback that it would be helpful to show HUC 8 names.   If this isn't available via the services let me know and we'll create a lookup json

**Comment by kjacobsen16** [comment]
@marsmith I'm not seeing it in the services anywhere, but does this look right:
```
{
    "02030201": "Northern Long Island",
    "02030202": "Southern Long Island",
    "02030104": "Sandy Hook-Staten Island",
    "02030203": "Long Island Sound"
}
```
it's based off of the huc8 that show up as options in the app compared with https://water.usgs.gov/GIS/wbd_huc8.pdf

**Comment by marsmith** [comment]
Yep! looks right

**Comment by kjacobsen16** [comment]
huc8 name now added to sidebar filter dropdown
