### ISSUE TITLE
Explore options for reducing filter change load time

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/LIQWIDS#118]
From user feedback: "Each time you select a parameter it takes time to re-pull the data.  If the user wants multiple or all the parameters, this slows things down considerably.  Option 1: Can we have a select all choice?  Option 2: Maybe have an Apply Changes button.  Any other thoughts on this?"

selection and data loading could be asynchronous?

**Comment by kjacobsen16** [comment]
implemented an 'apply changes' button
