### ISSUE TITLE
Filter the green triangle NWIS sites to just long island, allow for click queries

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/LIQWIDS#12]
![image](https://user-images.githubusercontent.com/6529123/53044787-fba2e080-3459-11e9-98b2-23e784a44ba8.png)

It's possible were just better off using NWIS waterservices for displaying these, like in FEV viewer.  Not sure how up to date this site list is

**Comment by esmyers** [comment]
it seems that these sites don't have a state attributes.  We'll probably have to look into the way that FEV does it, unless I can figure out some way to query their geoserver.  https://www.waterqualitydata.us/ogcservices/wfs/?request=GetFeature&service=wfs&version=2.0.0&typeNames=qw_portal_map:nwis_sites&SEARCHPARAMS=statecode%3AUS%3A36&outputFormat=application%2Fjson

**Comment by marsmith** [comment]
Lets table this for now, showing NWIS sites was never a requirement as far as I know.  Maybe turn them off?

**Comment by marsmith** [comment]
Stubbed in NWIS waterservices request, closing for now
