### ISSUE TITLE
Some issues loading page in firefox

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/LIQWIDS#17]
Sidebar is too narrow and there seems to be a CSS issue with a gray bar on the  bottom of the leaflet map.  In the screenshot below, bottom window is firefox:

![image](https://user-images.githubusercontent.com/6529123/53097004-70275f00-34ee-11e9-8d1d-da643fd30567.png)

**Comment by marsmith** [comment]
Resizing the page a tiny bit after load fixes both issues, may be a clue

**Comment by esmyers** [comment]
Agreed.  The sidebar is only messed up if I initialize it on a small (13") screen.
