### ISSUE TITLE
Ability to export/download a printable 'report'

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/LIQWIDS#23]

**Comment by kjacobsen16** [comment]
@marsmith is this separate from #10?

**Comment by marsmith** [comment]
Yes.  This one is like a printable 'screen capture' with a map, graphs, and table.   Similar to the streamstats report 'print' button.   Something the cooperator mentioned on the last call.

**Comment by HansVraga** [comment]
This is in progress. Looks like we need to add the map to this report

**Comment by HansVraga** [comment]
Complete
