### ISSUE TITLE
Update Dashbaord tab in About

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/LIQWIDS#45]
- [x] Rename "Dashboard" to "Contributing Organizations"

- [x] Add a "Water Quality Portal" title/header to the table
(eventually we'll have another table with LIQWIDS DB partners/info for authenticated users, and will want to differentiate between them)

- [ ] Look to query endpoints at wqp-test.er.usgs.gov to get a live org count (example Query https://wqp-test.er.usgs.gov/data/summary/organization/search?mimeType=json&summaryYears=5&organization=WIDNR_WQX )

**Comment by kjacobsen16** [comment]
the wqp-test.er.usgs.gov Summary Organization query doesn't limit by location, so we're unable to use that. I updated the totals to the actual all-time totals, and removed the summaryYears=5 filter
