### ISSUE TITLE
clear selection button needs double click to function properly

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/LIQWIDS#46]
Something about the inputs.scss before/after functions appears to be blocking the ng click event.

clicking the clear button 1x closes the filter, the second time it fires the clearForm() function.

**Comment by esmyers** [comment]
i don't know why, but it appears that the after pseudo-selector in the CSS is causing the clearForm() call to be unreachable.

**Comment by marsmith** [comment]
This got fixed with the new ng-select dropdowns
