### ISSUE TITLE
Discrepancy between 'resultCnt' on geojson and actual results in the graph/CSV

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/LIQWIDS#52]
see photo:
![image](https://user-images.githubusercontent.com/6529123/53888022-75f26980-3ff1-11e9-9f39-c449a183d4e8.png)

**Comment by kjacobsen16** [comment]
@marsmith I think this is an issue with overlapping results, since most of them for this site have the same date. I'll see if there's a way to handle that with Highcharts.
