### ISSUE TITLE
When all parameter filters are deselected, site is still selected in hash and data view

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/LIQWIDS#76]
![image](https://user-images.githubusercontent.com/6529123/55492885-f82c7880-5605-11e9-9b2a-0764e8478a07.png)

**Comment by marsmith** [comment]
I also notice in my screenshot above it says "13090 sites showing" ? and map zoomed to middle of atlantic

**Comment by kjacobsen16** [comment]
issue was only occurring when a site was in the URL on load, fixed the issue
