### ISSUE TITLE
De-selecting all Parameter Filters zooms map to somewhere in the Atlantic

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/LIQWIDS#77]
Also, when I click one of the 13,000 sites its showing a regression line, but what is that regression line for now that all parameters are showing?

![image](https://user-images.githubusercontent.com/6529123/55493395-dda6cf00-5606-11e9-986a-50747d485241.png)

**Comment by kjacobsen16** [comment]
when none selected, switch back to default
