### ISSUE TITLE
Investigate water navigation basemap

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/LIQWIDS#81]
(something that has approximate depth)

**Comment by marsmith** [comment]
https://nauticalcharts.noaa.gov/data/gis-data-and-services.html#seamless-raster-nautical-chart-services

http://www.arcgis.com/home/webmap/viewer.html?url=http%3A%2F%2Fseamlessrnc.nauticalcharts.noaa.gov%2Farcgis%2Frest%2Fservices%2FRNC%2FNOAA_RNC%2FImageServer&source=sd

**Comment by kjacobsen16** [comment]
done
