### ISSUE TITLE
Use http get "URLparams" object for parameters instead of adding them to URL string

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/LIQWIDS#88]
Like with geoJSON request here:

https://github.com/USGS-WiM/LIQWIDS/blob/28bb2bee4b0c73f3012d4f8d3394563a49de16b9/src/app/shared/services/map.service.ts#L136

**Comment by kjacobsen16** [comment]
I think I'm misunderstanding this one. I'm confused by the "instead of adding them to URL string" part. Don't we need them in the URL?

**Comment by kjacobsen16** [comment]
this is referencing the "result" query in the dataview component, use the urlParams object from the map.service and add the site and characteristic for it in order to remove the hardcoded url/parameters from the project
