### ISSUE TITLE
Add more data / help data on the parameters 

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/LIQWIDS#95]
WQP offers definitions for all parameters - we should pull those definitions for parameters we feature in liqwids and offer a 'i' or '?' icon next to parameters that then provides that information in some way (either as a single pop-up for that parm, or opens to a table of all params with that param visible)

**Comment by HansVraga** [comment]
Mitch has a couple of solutions ready - we're looking into the typical length of these descriptions

**Comment by jknewson** [comment]
Not sure if this helps, but here are a bunch of data pulls from WQP that I started compiling for seeding the database https://github.com/USGS-WiM/LiqwidsServices/tree/staging/LiqwidsDB/Data

**Comment by HansVraga** [comment]
Chased this in a circle today - @marsmith do you remember what this is?

**Comment by marsmith** [comment]
Hans emailed about this will report back

**Comment by HansVraga** [comment]
This turned out to be a wild goose chase. No param definitions apparently exist.
