### ISSUE TITLE
Enable saving of graphs

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/LIQWIDS#99]
From cooperator:
> I was also wondering if the graphs could be saved like at other USGS sites such as https://waterdata.usgs.gov/nwis/dv?referred_module=sw&site_no=01427510 .  Here you can right click & save image & also has a presentation quality option.

**Comment by HansVraga** [comment]
An example:
Similar functionality available in Sparrow graphs:
![image](https://user-images.githubusercontent.com/12058013/57231801-44921c00-6fe9-11e9-9a90-8c5e4ec70edb.png)

**Comment by esmyers** [comment]
Will Take a look at this.  There are a couple of extensions that do this.  To get the CSV or XLS we'd use the export data module.  https://www.highcharts.com/docs/export-module/export-module-overview

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/export-data/categorized/

**Comment by kjacobsen16** [comment]
added
